### ISSUE TITLE
Can't get delete_watched_TV.py to work

### ISSUE THREAD

**Issue by herrwusel** [blacktwin/JBOPS#119]
First of all thanks for your scripts! I'm trying to get `delete_watched_TV.py` working. When I run the script manually in cmd it shows me this:
> Tautulli API 'get_history' request failed: No JSON object could be decoded.Tautulli API 'get_history' request failed: No JSON object could be decoded.

I don't see what I did wrong. Can you give me a hint? Thanks!

EDIT: I tried the api call manually with the non local https ip and then it is working. When I change the it in your script to `https://IP/tautulli/` I get:

> Tautulli API 'get_history' request failed: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //IP/tautulli/api/v2?apikey=xx&cmd=get_history&start=0&length=25&user=xx&grandparent_rating_key=24 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5f53534610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)).Tautulli API 'get_history' request failed: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //xx/tautulli/api/v2?apikey=xx&cmd=get_history&start=0&length=25&user=xx&grandparent_rating_key=21 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5f53534690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)).

**Comment by blacktwin** [comment]
Check your URL and APIKEY.

**Comment by herrwusel** [comment]
It seems that I can't connect to the external IP but internal works for now. 
But another problem appeared. When the script tries to access the metadata with `.../tautulli/api/v2?cmd=get_metadata&media_info=True&apikey=xx&rating_key=24` there is the 'metadata' missing:

> Tautulli API 'get_metadata' request failed: 'metadata'.'NoneType' object has no attribute 'title'
Tautulli API 'get_metadata' request failed: 'metadata'.'NoneType' object has no attribute 'title'

I did run the command in the python console and I got data but as mentioned above there is no metadata entry.

**Comment by blacktwin** [comment]
Ok. Sorry looks like I missed one when updating from PlexPy to Tautull. The metadata structure changed. I've updated the script. Please try again and let me know.

**Comment by herrwusel** [comment]
Hijacking this old issue. I still get a lot of this when running the script as root:
```bash
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
```
When I test the script in tautulli I get this comes up as an error:
```bash

2018-11-25 11:14:08 | ERROR | Tautulli Notifiers :: Script error:     Tautulli  API 'get_metadata' request failed: 'title'.Tautulli API 'get_metadata'  request failed: 'title'.Tautulli API 'get_metadata' request failed:  'title'.Tautulli API 'get_metadata' request failed: 'title'.Tautulli API  'get_metadata' request failed: 'title'.Tautulli API 'get_metadata'  request failed: 'title'.Tautulli API 'get_metadata' request failed:  'title'.
```

**Comment by blacktwin** [comment]
Do the same thing for the `get_history` function.

**Comment by herrwusel** [comment]
```bash
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'43 mins', u'recordsTotal': 24, u'recordsFiltered': 1, u'data': [{u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 0, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 25, u'parent_title': u'Season 15', u'duration': 2557, u'session_key': None, u'transcode_decision': u'direct play', u'id': 1, u'user_id': 228889, u'thumb': u'/library/metadata/25/thumb/1542382630', u'title': u'Season 15', u'rating_key': 26, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 24, u'started': 1542453648, u'group_count': 1, u'reference_id': 1, u'date': 1542453648, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'1', u'media_index': 8, u'original_title': u'', u'full_title': u"Grey's Anatomy - Blowin' in the Wind", u'stopped': 1542456205, u'grandparent_title': u"Grey's Anatomy", u'parent_media_index': 15, u'user': u'user1'}], u'filter_duration': u'43 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'43 mins', u'recordsTotal': 24, u'recordsFiltered': 1, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'24 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [{u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 0, u'watched_status': 0, u'player': u'Firefox', u'parent_rating_key': 22, u'parent_title': u'Season 12', u'duration': 236, u'session_key': None, u'transcode_decision': u'transcode', u'id': 3, u'user_id': 228889, u'thumb': u'/library/metadata/22/thumb/1542382631', u'title': u'Season 12', u'rating_key': 23, u'platform': u'Firefox', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 21, u'started': 1542472633, u'group_count': 1, u'reference_id': 3, u'date': 1542472633, u'percent_complete': 0, u'ip_address': u'ip', u'group_ids': u'3', u'media_index': 9, u'original_title': u'', u'full_title': u'The Big Bang Theory - The Citation Negation', u'stopped': 1542472869, u'grandparent_title': u'The Big Bang Theory', u'parent_media_index': 12, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 73, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 22, u'parent_title': u'Season 12', u'duration': 1231, u'session_key': None, u'transcode_decision': u'direct play', u'id': 2, u'user_id': 228889, u'thumb': u'/library/metadata/22/thumb/1542382631', u'title': u'Season 12', u'rating_key': 23, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 21, u'started': 1542456215, u'group_count': 1, u'reference_id': 2, u'date': 1542456215, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'2', u'media_index': 9, u'original_title': u'', u'full_title': u'The Big Bang Theory - The Citation Negation', u'stopped': 1542457519, u'grandparent_title': u'The Big Bang Theory', u'parent_media_index': 12, u'user': u'user1'}], u'filter_duration': u'24 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'24 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'3 hrs 8 mins', u'recordsTotal': 24, u'recordsFiltered': 4, u'data': [{u'friendly_name': u'user1', u'year': 2017, u'paused_counter': 0, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 4, u'parent_title': u'Season 1', u'duration': 3043, u'session_key': None, u'transcode_decision': u'direct play', u'id': 12, u'user_id': 228889, u'thumb': u'/library/metadata/3/thumb/1542351297', u'title': u'Season 1', u'rating_key': 8, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 3, u'started': 1542834074, u'group_count': 1, u'reference_id': 12, u'date': 1542834074, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'12', u'media_index': 4, u'original_title': u'', u'full_title': u'Money Heist - Episode 4', u'stopped': 1542837117, u'grandparent_title': u'Money Heist', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2017, u'paused_counter': 126, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 4, u'parent_title': u'Season 1', u'duration': 2999, u'session_key': None, u'transcode_decision': u'direct play', u'id': 9, u'user_id': 228889, u'thumb': u'/library/metadata/3/thumb/1542351297', u'title': u'Season 1', u'rating_key': 7, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 3, u'started': 1542657757, u'group_count': 1, u'reference_id': 9, u'date': 1542657757, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'9', u'media_index': 3, u'original_title': u'', u'full_title': u'Money Heist - Episode 3', u'stopped': 1542660882, u'grandparent_title': u'Money Heist', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2017, u'paused_counter': 0, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 4, u'parent_title': u'Season 1', u'duration': 2445, u'session_key': None, u'transcode_decision': u'direct play', u'id': 7, u'user_id': 228889, u'thumb': u'/library/metadata/3/thumb/1542351297', u'title': u'Season 1', u'rating_key': 6, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 3, u'started': 1542576494, u'group_count': 1, u'reference_id': 7, u'date': 1542576494, u'percent_complete': 100, u'ip_address': u'ip', u'group_ids': u'7', u'media_index': 2, u'original_title': u'', u'full_title': u'Money Heist - Episode 2', u'stopped': 1542578939, u'grandparent_title': u'Money Heist', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2017, u'paused_counter': 0, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 4, u'parent_title': u'Season 1', u'duration': 2812, u'session_key': None, u'transcode_decision': u'direct play', u'id': 6, u'user_id': 228889, u'thumb': u'/library/metadata/3/thumb/1542351297', u'title': u'Season 1', u'rating_key': 5, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 3, u'started': 1542573667, u'group_count': 1, u'reference_id': 6, u'date': 1542573667, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'6', u'media_index': 1, u'original_title': u'', u'full_title': u'Money Heist - Episode 1', u'stopped': 1542576479, u'grandparent_title': u'Money Heist', u'parent_media_index': 1, u'user': u'user1'}], u'filter_duration': u'3 hrs 8 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'3 hrs 8 mins', u'recordsTotal': 24, u'recordsFiltered': 4, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'21 mins', u'recordsTotal': 24, u'recordsFiltered': 1, u'data': [{u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 126, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 157, u'parent_title': u'Season 30', u'duration': 1280, u'session_key': None, u'transcode_decision': u'direct play', u'id': 8, u'user_id': 228889, u'thumb': u'/library/metadata/157/thumb/1542620375', u'title': u'Season 30', u'rating_key': 158, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 156, u'started': 1542648191, u'group_count': 1, u'reference_id': 8, u'date': 1542648191, u'percent_complete': 98, u'ip_address': u'ip', u'group_ids': u'8', u'media_index': 7, u'original_title': u'', u'full_title': u'The Simpsons - Werking Mom', u'stopped': 1542649597, u'grandparent_title': u'The Simpsons', u'parent_media_index': 30, u'user': u'user1'}], u'filter_duration': u'21 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'21 mins', u'recordsTotal': 24, u'recordsFiltered': 1, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'44 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [{u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 0, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 190, u'parent_title': u'Season 1', u'duration': 1304, u'session_key': None, u'transcode_decision': u'direct play', u'id': 17, u'user_id': 228889, u'thumb': u'/library/metadata/189/thumb/1542959207', u'title': u'Season 1', u'rating_key': 213, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 189, u'started': 1543073333, u'group_count': 1, u'reference_id': 17, u'date': 1543073333, u'percent_complete': 100, u'ip_address': u'ip', u'group_ids': u'17', u'media_index': 2, u'original_title': u'', u'full_title': u'I Feel Bad - I Get Sick of Being Needed', u'stopped': 1543074637, u'grandparent_title': u'I Feel Bad', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 277, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 190, u'parent_title': u'Season 1', u'duration': 1306, u'session_key': None, u'transcode_decision': u'direct play', u'id': 16, u'user_id': 228889, u'thumb': u'/library/metadata/189/thumb/1542959207', u'title': u'Season 1', u'rating_key': 191, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 189, u'started': 1543071723, u'group_count': 1, u'reference_id': 16, u'date': 1543071723, u'percent_complete': 100, u'ip_address': u'ip', u'group_ids': u'16', u'media_index': 1, u'original_title': u'', u'full_title': u"I Feel Bad - I Don't Want to Turn into My Mother", u'stopped': 1543073306, u'grandparent_title': u'I Feel Bad', u'parent_media_index': 1, u'user': u'user1'}], u'filter_duration': u'44 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'44 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'49 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [{u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 0, u'watched_status': 1, u'player': u'Firefox', u'parent_rating_key': 186, u'parent_title': u'Season 1', u'duration': 353, u'session_key': None, u'transcode_decision': u'transcode', u'id': 22, u'user_id': 228889, u'thumb': u'/library/metadata/186/thumb/1542959440', u'title': u'Season 1', u'rating_key': 188, u'platform': u'Firefox', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 185, u'started': 1543141255, u'group_count': 1, u'reference_id': 22, u'date': 1543141255, u'percent_complete': 100, u'ip_address': u'ip', u'group_ids': u'22', u'media_index': 2, u'original_title': u'', u'full_title': u'The Rookie - Crash Course', u'stopped': 1543141608, u'grandparent_title': u'The Rookie', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2018, u'paused_counter': 497, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 186, u'parent_title': u'Season 1', u'duration': 2586, u'session_key': None, u'transcode_decision': u'direct play', u'id': 15, u'user_id': 228889, u'thumb': u'/library/metadata/186/thumb/1542959440', u'title': u'Season 1', u'rating_key': 187, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 185, u'started': 1543068451, u'group_count': 2, u'reference_id': 14, u'date': 1543070697, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'14,15', u'media_index': 1, u'original_title': u'', u'full_title': u'The Rookie - Pilot', u'stopped': 1543071607, u'grandparent_title': u'The Rookie', u'parent_media_index': 1, u'user': u'user1'}], u'filter_duration': u'49 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'49 mins', u'recordsTotal': 24, u'recordsFiltered': 2, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'2 hrs 9 mins', u'recordsTotal': 24, u'recordsFiltered': 3, u'data': [{u'friendly_name': u'user1', u'year': 2016, u'paused_counter': 703, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 193, u'parent_title': u'Season 1', u'duration': 2589, u'session_key': None, u'transcode_decision': u'direct play', u'id': 20, u'user_id': 228889, u'thumb': u'/library/metadata/193/thumb/1542958965', u'title': u'Season 1', u'rating_key': 196, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 192, u'started': 1543095494, u'group_count': 1, u'reference_id': 20, u'date': 1543095494, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'20', u'media_index': 3, u'original_title': u'', u'full_title': u'This Is Us - Kyle', u'stopped': 1543098786, u'grandparent_title': u'This Is Us', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2016, u'paused_counter': 98, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 193, u'parent_title': u'Season 1', u'duration': 2595, u'session_key': None, u'transcode_decision': u'direct play', u'id': 19, u'user_id': 228889, u'thumb': u'/library/metadata/193/thumb/1542958965', u'title': u'Season 1', u'rating_key': 195, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 192, u'started': 1543092788, u'group_count': 1, u'reference_id': 19, u'date': 1543092788, u'percent_complete': 100, u'ip_address': u'ip', u'group_ids': u'19', u'media_index': 2, u'original_title': u'', u'full_title': u'This Is Us - The Big Three', u'stopped': 1543095481, u'grandparent_title': u'This Is Us', u'parent_media_index': 1, u'user': u'user1'}, {u'friendly_name': u'user1', u'year': 2016, u'paused_counter': 3973, u'watched_status': 1, u'player': u'PlexKodiConnect', u'parent_rating_key': 193, u'parent_title': u'Season 1', u'duration': 2557, u'session_key': None, u'transcode_decision': u'direct play', u'id': 18, u'user_id': 228889, u'thumb': u'/library/metadata/193/thumb/1542958965', u'title': u'Season 1', u'rating_key': 194, u'platform': u'Linux', u'state': None, u'media_type': u'episode', u'grandparent_rating_key': 192, u'started': 1543085973, u'group_count': 1, u'reference_id': 18, u'date': 1543085973, u'percent_complete': 99, u'ip_address': u'ip', u'group_ids': u'18', u'media_index': 1, u'original_title': u'', u'full_title': u'This Is Us - Pilot', u'stopped': 1543092503, u'grandparent_title': u'This Is Us', u'parent_media_index': 1, u'user': u'user1'}], u'filter_duration': u'2 hrs 9 mins'}, u'result': u'success'}}
{u'response': {u'message': None, u'data': {}, u'result': u'error'}}
Tautulli API 'get_metadata' request failed: 'title'.'NoneType' object has no attribute 'title'
{u'response': {u'message': None, u'data': {u'draw': 1, u'total_duration': u'2 hrs 9 mins', u'recordsTotal': 24, u'recordsFiltered': 3, u'data': [], u'filter_duration': u'0'}, u'result': u'success'}}
```

**Comment by blacktwin** [comment]
Can check those rating_keys and check that they exist?

**Comment by herrwusel** [comment]
I double checked but what if this script deletes the last episode physically available? Does the show including rating key disappear and therefore maybe throwing this error?

**Comment by blacktwin** [comment]
The history should always exist unless manually deleted. The rating key can be delete or removed if the item is deleted and Plex has Emptied Trash and therefore Tautulli is updated. This script only touches Tautulli.

Each item has it's own rating key include the show and season. So if the Show or Season rating keys were deleted then that might be the issue.

**Comment by herrwusel** [comment]
The deleting is working for me and I can try to fill in episodes to see if that fixes the warnings later this week. I close the issue for now and report back. Thanks for the help again!
